export const types = {
    PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
    PRODUCTS_FAILURE: 'PRODUCTS_FAILURE',
    PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
    PRELOAD_PRODUCTS: 'PRELOAD_PRODUCTS',
    PRODUCTS_LOADMORE: 'PRODUCTS_LOADMORE'
}
